(deftheme geeko
  "Dark theme based on openSUSE palette.")

(custom-theme-set-faces
 'geeko
 '(bold ((t (:bold t))))
 '(bold-italic ((t (:slant italic :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#b9dc92" :weight normal))))
 '(font-lock-comment-face ((t (:foreground "#8b9fa7" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#6da741"))))
 '(font-lock-function-name-face ((t (:foreground "#7fd1c4"))))
 '(font-lock-keyword-face ((t (:foreground "#73ba25" :weight semi-bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#8b9fa7" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#ccedea"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#dceec8"))))
 '(org-hide ((t (:foreground "#173f4f"))))
 '(org-level-1 ((t (:background "#516f7b" :foreground "#73ba25" :weight normal :height 1.4))))
 '(org-level-2 ((t (:background "#516f7b" :foreground "#b9dc92" :weight normal :height 1.3))))
 '(org-level-3 ((t (:background "#516f7b" :foreground "#00a489" :weight normal :height 1.2))))
 '(org-level-4 ((t (:background "#516f7b" :foreground "#7fd1c4" :weight normal :height 1.1))))
 '(org-date ((t (:foreground "#90d1ef"))))
 '(org-footnote ((t (:foreground "#38ade2"))))
 '(org-link ((t (:foreground "#dceec8" nil :underline (:color "#dceec8" :style nil)))))
 '(org-special-keyword ((t (:foreground "#96cb5c"))))
 '(org-verbatim ((t (:foreground "#c5cfd3"))))
 '(org-block ((t (:background "#dceec8" :foreground "#516f7b"))))
 '(org-quote ((t (:background "#dceec8" :inherit org-block :slant italic))))
 '(org-verse ((t (:background "#dceec8" :inherit org-block :slant italic))))
 '(org-todo ((t (:background "#516f7b" :foreground "#21a4df" :weight bold))))
 '(org-done ((t (:background "#516f7b" :foreground "#6da741" :weight bold))))
 '(org-agenda-structure ((t (:foreground "#9adcd5" :weight bold))))
 '(org-agenda-date ((t (:foreground "#68cbc0"))))
 '(org-agenda-date-weekend ((t (:foreground "#4ac0b4" :weight normal))))
 '(org-agenda-date-today ((t (:foreground "#ccedea" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#b9dc92"))))
 '(font-lock-type-face ((t (:foreground "#21afdf"))))
 '(font-lock-variable-name-face ((t (:foreground "#59bbe7"))))
 '(font-lock-warning-face ((t (:foreground "#fcefa1" :weight bold))))
 '(region ((t (:background "#516f7b"))))
 '(mode-line ((t (:box (:line-width 1 :color "#35b9ab") :foreground "#73ba25" :background "#173f4f"))))
 '(highlight ((t (:background "#2f5361"))))
 '(italic ((t (nil))))
 '(underline ((t (:underline t))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#173f4f" :foreground "#b9dc92" :box (:line-width 1 :color "#35b9ab") :weight medium))))
 '(fringe ((t (:background "#173f4f"))))
 '(org-block-begin-line ((t (:background "#516f7b" :inherit org-meta-line))))
 '(org-meta-line ((t (:inherit (font-lock-comment-face)))))
 '(org-block-end-line ((t (:inherit org-meta-line :background "#516f7b"))))
 '(default ((t (:background "#173f4f" :foreground "#35b9ab"))))
 '(term ((t (:inherit default :background "#173f4f" :foreground "#c5cfd3")))))

(provide-theme 'geeko)
